---
#-------------------------------
# General Site Settings

title: Assign 1 Group 5
logo: 
author: Group 5
description: this is meta description
email: picdictgroup5@163.com
phone: +852 5980 3331
address: Tat Chee Avenue, Hong Kong
copyright: Copyright &copy; 2023 Designed by [Zhengwu MA](https://zhengwuma.github.io/) & Developed by [Get jekyll themes](https://getjekyllthemes.com)

menu:
  - { name: About, link: "/about" }
  - { name: Pictionary, link: "/blog" }
  - { name: Portfolio, link: "/portfolio" }
  - { name: Contact, link: "/contact" }

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

google-analytics: # UA-XXXXXX-X

#-------------------------------
# Comment Section (Disqus)

disqus-identifier: # Add your shortname for Disqus Comment. For example mr-brown

#-------------------------------
# Hero Section

hero:
  hero-title: Welcome to <br> Pictionary! <br> <i>Let's enter the digital learning scenario!</i>


#-------------------------------
# About (Section and Page)

# About Section
blurb: We learn from the tangible world, including the language. Pictionary is the primary school students domain dictionary project to collect the real objects around our world. This work is developed by the 2023 spring LT5457 Compuational Lexicography Group 5.

blurb-btn-link: "/about"
blurb-btn-name: know more

# About Page

# Work Process Section
work-process:
  - title: "Research and Plan"
    icon: "assets/images/icons/plan.png"
    content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."

  - title: "Design and Develop"
    icon: "assets/images/icons/design.png"
    content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."

  - title: "Deliver"
    icon: "assets/images/icons/print.png"
    content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."

# My Team Section
team:
  - title: "Zhengwu MA"
    image: "assets/images/team/member-1.png"
    designation: "Web Developer"

  - title: "Lu CHEN"
    image: "assets/images/team/member-2.png"
    designation: "IPA Collection"

  - title: "Yanjun LAI"
    image: "assets/images/team/member-3.png"
    designation: " "
    
  - title: "Yinrong YAN"
    image: "assets/images/team/member-3.png"
    designation: "Word Phrases Collocation Collection"
    
  - title: "Huiyi ZHENG"
    image: "assets/images/team/member-3.png"
    designation: " "
    
  - title: "Minglin LI"
    image: "assets/images/team/member-3.png"
    designation: "Image Collection"


# Portfolio (Section and Page)

# Portfolio Home Section
portfolio-home-items:
  - image: "assets/images/portfolio/item-1.png"
    url: "#"

  - image: "assets/images/portfolio/item-2.png"
    url: "#"

  - image: "assets/images/portfolio/item-3.png"
    url: "#"

  - image: "assets/images/portfolio/item-4.png"
    url: "#"

  - image: "assets/images/portfolio/item-5.png"
    url: "#"

# Portfolio Page
portfolio-label:
  - { title: "UI/UX Design", type: "design" }
  - { title: "BRANDING", type: "branding" }
  - { title: "ILLUSTRATION", type: "illustration" }

portfolio-items:
  - image: "assets/images/portfolio/item-1.png"
    url: "#"
    portfolio-type:
      - type: "design"
      - type: "illustration"

  - image: "assets/images/portfolio/item-2.png"
    url: "#"
    portfolio-type:
      - type: "branding"

  - image: "assets/images/portfolio/item-3.png"
    url: "#"
    portfolio-type:
      - type: "illustration"

  - image: "assets/images/portfolio/item-6.png"
    url: "#"
    portfolio-type:
      - type: "design"
      - type: "branding"

  - image: "assets/images/portfolio/item-8.png"
    url: "#"
    portfolio-type:
      - type: "illustration"

  - image: "assets/images/portfolio/item-5.png"
    url: "#"
    portfolio-type:
      - type: "design"

  - image: "assets/images/portfolio/item-1.png"
    url: "#"
    portfolio-type:
      - type: "branding"

  - image: "assets/images/portfolio/item-3.png"
    url: "#"
    portfolio-type:
      - type: "design"
      - type: "illustration"
      - type: "branding"

  - image: "assets/images/portfolio/item-7.png"
    url: "#"
    portfolio-type:
      - type: "illustration"


#-------------------------------
# Contact Section

contact-title: Contact Info
contact-email: picdictgroup5@163.com
